services:
  nessie-catalog:
    image: projectnessie/nessie:0.76.6
    container_name: nessie-catalog
    ports:
      - "19120:19120"

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_REGION: us-east-1
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address ':9001' &
      sleep 5;
      mc alias set admin http://minio:9000 minioadmin miniopassword;
      mc mb admin/lakehouse;
      tail -f /dev/null"

  trino-coordinator:
    image: trinodb/trino:476
    container_name: trino-coordinator
    ports:
      - "9080:8080"
    volumes:
      - ./trino/coordinator/config.properties:/etc/trino/config.properties
      - ./trino/catalog:/etc/trino/catalog
      - ./trino/coordinator/init.sql:/etc/trino/init.sql
    depends_on:
      - nessie-catalog
      - minio
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/info"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  trino-worker-1:
    image: trinodb/trino:476
    container_name: trino-worker-1
    volumes:
      - ./trino/worker/config.properties:/etc/trino/config.properties
      - ./trino/catalog:/etc/trino/catalog
    depends_on:
      - trino-coordinator
#  trino-worker-2:
#    image: trinodb/trino:476
#    container_name: trino-worker-2
#    volumes:
#      - ./trino/worker/config.properties:/etc/trino/config.properties
#      - ./trino/catalog:/etc/trino/catalog
#    depends_on:
#      - trino-coordinator
#
#  trino-worker-3:
#    image: trinodb/trino:476
#    container_name: trino-worker-3
#    volumes:
#      - ./trino/worker/config.properties:/etc/trino/config.properties
#      - ./trino/catalog:/etc/trino/catalog
#    depends_on:
#      - trino-coordinator

