ecommerce_dbt:
  outputs:
    trino:
      type: trino
      method: none
      user: admin
      database: iceberg
      # host: host.docker.internal
      host: localhost
      port: 9080
      schema: bronze
      threads: 3
  target: trino
# ecommerce_dbt:
#   outputs:
#     trino:
#       type: trino
#       method: none
#       user: admin
#       database: iceberg
#       host: trino-coordinator
#       port: 8080
#       schema: bronze
#       threads: 1
#   target: trino
